export const LINUX_POPUP_PY = [
  "import json",
  "import os",
  "import tkinter as tk",
  "style = json.loads(os.environ.get('POPUP_STYLE', '{}'))",
  "title = os.environ.get('POPUP_TITLE', 'OpenCode')",
  "message = os.environ.get('POPUP_MESSAGE', '')",
  "colors = style.get('blinkColors') or ['#FFC800']",
  "foreground = style.get('textColor', '#111111')",
  "font_family = style.get('fontFamily', 'Sans')",
  "font_size = int(style.get('fontSize', 12))",
  "opacity = max(0.2, min(1.0, float(style.get('opacity', 1))))",
  "interval = max(100, int(style.get('blinkIntervalMs', 600)))",
  "image = style.get('image') or {}",
  "image_enabled = bool(image.get('enabled'))",
  "image_path = image.get('path') or ''",
  "image_position = 'right' if image.get('position') == 'right' else 'left'",
  "root = tk.Tk()",
  "root.withdraw()",
  "root.title(title)",
  "root.overrideredirect(True)",
  "try:",
  "    root.wm_attributes('-type', 'notification')",
  "except tk.TclError:",
  "    pass",
  "try:",
  "    root.attributes('-topmost', True)",
  "    root.attributes('-alpha', opacity)",
  "except tk.TclError:",
  "    pass",
  "root.configure(bg=colors[0])",
  "container = tk.Frame(root, bg=colors[0], borderwidth=0, highlightthickness=0)",
  "container.pack()",
  "label = tk.Label(container, text=title + '\\n\\n' + message, bg=colors[0], fg=foreground, font=(font_family, font_size), borderwidth=0, highlightthickness=0, justify='left')",
  "image_photo = None",
  "image_label = None",
  "if image_enabled and image_path:",
  "    try:",
  "        image_photo = tk.PhotoImage(file=image_path)",
  "        if image_photo.width() != 64 or image_photo.height() != 64:",
  "            raise ValueError('PNG must be 64x64')",
  "    except (tk.TclError, ValueError):",
  "        image_photo = None",
  "if image_photo is not None:",
  "    image_label = tk.Label(container, image=image_photo, bg=colors[0], borderwidth=0, highlightthickness=0)",
  "    if image_position == 'right':",
  "        label.pack(side='left', padx=(20, 12), pady=20)",
  "        image_label.pack(side='left', padx=(0, 20), pady=20)",
  "    else:",
  "        image_label.pack(side='left', padx=(20, 0), pady=20)",
  "        label.pack(side='left', padx=(12, 20), pady=20)",
  "else:",
  "    label.pack(padx=20, pady=20)",
  "root.update_idletasks()",
  "x = max(0, (root.winfo_screenwidth() - root.winfo_reqwidth()) // 2)",
  "y = max(0, (root.winfo_screenheight() - root.winfo_reqheight()) // 2)",
  "root.geometry('+' + str(x) + '+' + str(y))",
  "def close_popup(_event=None):",
  "    root.destroy()",
  "root.bind('<Button-1>', close_popup)",
  "container.bind('<Button-1>', close_popup)",
  "label.bind('<Button-1>', close_popup)",
  "if image_label is not None:",
  "    image_label.bind('<Button-1>', close_popup)",
  "color_index = 0",
  "def blink():",
  "    global color_index",
  "    if len(colors) > 1:",
  "        color_index = (color_index + 1) % len(colors)",
  "        color = colors[color_index]",
  "        root.configure(bg=color)",
  "        container.configure(bg=color)",
  "        label.configure(bg=color)",
  "        if image_label is not None:",
  "            image_label.configure(bg=color)",
  "    root.after(interval, blink)",
  "root.deiconify()",
  "root.after(interval, blink)",
  "root.mainloop()",
].join("\n");

export const LINUX_POPUP_SH = [
  "if command -v python3 >/dev/null 2>&1 && python3 -c 'import tkinter' >/dev/null 2>&1; then",
  "  exec python3 -c \"$POPUP_LINUX_SCRIPT\"",
  "elif command -v zenity >/dev/null 2>&1; then",
  "  if [ -n \"$POPUP_IMAGE_PATH\" ]; then",
  "    exec zenity --info --title=\"$POPUP_TITLE\" --text=\"$POPUP_MESSAGE\" --no-wrap --window-icon=\"$POPUP_IMAGE_PATH\"",
  "  fi",
  "  exec zenity --info --title=\"$POPUP_TITLE\" --text=\"$POPUP_MESSAGE\" --no-wrap",
  "else",
  "  if [ -n \"$POPUP_IMAGE_PATH\" ]; then",
  "    exec notify-send -u critical -t 0 -i \"$POPUP_IMAGE_PATH\" \"$POPUP_TITLE\" \"$POPUP_MESSAGE\"",
  "  fi",
  "  exec notify-send -u critical -t 0 \"$POPUP_TITLE\" \"$POPUP_MESSAGE\"",
  "fi",
].join("\n");
