export const LINUX_POPUP_PY = [
  "import json",
  "import os",
  "import tkinter as tk",
  "style = json.loads(os.environ.get('POPUP_STYLE', '{}'))",
  "title = os.environ.get('POPUP_TITLE', 'OpenCode')",
  "message = os.environ.get('POPUP_MESSAGE', '')",
  "colors = style.get('blinkColors') or ['#FFC800']",
  "foreground = style.get('textColor', '#111111')",
  "font_family = style.get('fontFamily', 'Sans')",
  "font_size = int(style.get('fontSize', 12))",
  "opacity = max(0.2, min(1.0, float(style.get('opacity', 1))))",
  "interval = max(100, int(style.get('blinkIntervalMs', 600)))",
  "root = tk.Tk()",
  "root.withdraw()",
  "root.title(title)",
  "root.overrideredirect(True)",
  "try:",
  "    root.wm_attributes('-type', 'notification')",
  "except tk.TclError:",
  "    pass",
  "try:",
  "    root.attributes('-topmost', True)",
  "    root.attributes('-alpha', opacity)",
  "except tk.TclError:",
  "    pass",
  "label = tk.Label(root, text=title + '\\n\\n' + message, bg=colors[0], fg=foreground, font=(font_family, font_size), padx=20, pady=20, justify='left')",
  "label.pack()",
  "root.update_idletasks()",
  "x = max(0, (root.winfo_screenwidth() - root.winfo_reqwidth()) // 2)",
  "y = max(0, (root.winfo_screenheight() - root.winfo_reqheight()) // 2)",
  "root.geometry('+' + str(x) + '+' + str(y))",
  "root.bind('<Button-1>', lambda _event: root.destroy())",
  "label.bind('<Button-1>', lambda _event: root.destroy())",
  "color_index = 0",
  "def blink():",
  "    global color_index",
  "    if len(colors) > 1:",
  "        color_index = (color_index + 1) % len(colors)",
  "        label.configure(bg=colors[color_index])",
  "    root.after(interval, blink)",
  "root.deiconify()",
  "root.after(interval, blink)",
  "root.mainloop()",
].join("\n");

export const LINUX_POPUP_SH = [
  "if command -v python3 >/dev/null 2>&1 && python3 -c 'import tkinter' >/dev/null 2>&1; then",
  "  exec python3 -c \"$POPUP_LINUX_SCRIPT\"",
  "elif command -v zenity >/dev/null 2>&1; then",
  "  exec zenity --info --title=\"$POPUP_TITLE\" --text=\"$POPUP_MESSAGE\" --no-wrap",
  "else",
  "  exec notify-send -u critical -t 0 \"$POPUP_TITLE\" \"$POPUP_MESSAGE\"",
  "fi",
].join("\n");
