export const LINUX_DEFAULT_SOUND_SH = [
  "sound_name=$1",
  "if command -v canberra-gtk-play >/dev/null 2>&1; then",
  "  exec canberra-gtk-play -i \"$sound_name\"",
  "fi",
  "freedesktop=/usr/share/sounds/freedesktop/stereo/complete.oga",
  "if [ -f \"$freedesktop\" ] && command -v paplay >/dev/null 2>&1; then",
  "  exec paplay \"$freedesktop\"",
  "fi",
  "if [ -f \"$freedesktop\" ] && command -v pw-play >/dev/null 2>&1; then",
  "  exec pw-play \"$freedesktop\"",
  "fi",
  "alsa=/usr/share/sounds/alsa/Front_Center.wav",
  "if [ -f \"$alsa\" ] && command -v aplay >/dev/null 2>&1; then",
  "  exec aplay -q \"$alsa\"",
  "fi",
  "if command -v beep >/dev/null 2>&1; then",
  "  exec beep -f 1000 -l 300",
  "fi",
  "exit 127",
].join("\n");

export const LINUX_FILE_SOUND_SH = [
  "sound_file=$1",
  "if command -v canberra-gtk-play >/dev/null 2>&1; then",
  "  exec canberra-gtk-play -f \"$sound_file\"",
  "elif command -v paplay >/dev/null 2>&1; then",
  "  exec paplay \"$sound_file\"",
  "elif command -v pw-play >/dev/null 2>&1; then",
  "  exec pw-play \"$sound_file\"",
  "elif command -v ffplay >/dev/null 2>&1; then",
  "  exec ffplay -nodisp -autoexit -loglevel quiet \"$sound_file\"",
  "elif command -v aplay >/dev/null 2>&1; then",
  "  exec aplay -q \"$sound_file\"",
  "fi",
  "exit 127",
].join("\n");
