export const FOCUSER_CS = [
  "using System;",
  "using System.Runtime.InteropServices;",
  "public class Focuser {",
  '  [DllImport("user32.dll")] public static extern bool SetForegroundWindow(IntPtr hWnd);',
  '  [DllImport("user32.dll")] public static extern IntPtr GetForegroundWindow();',
  '  [DllImport("user32.dll")] public static extern uint GetWindowThreadProcessId(IntPtr hWnd, out uint lpdwProcessId);',
  '  [DllImport("kernel32.dll")] public static extern uint GetCurrentThreadId();',
  '  [DllImport("user32.dll")] public static extern bool AttachThreadInput(uint idAttach, uint idAttachTo, bool fAttach);',
  '  [DllImport("user32.dll")] public static extern int GetWindowLong(IntPtr hWnd, int nIndex);',
  '  [DllImport("user32.dll")] public static extern int SetWindowLong(IntPtr hWnd, int nIndex, int dwNewLong);',
  '  [DllImport("user32.dll")] public static extern bool IsIconic(IntPtr hWnd);',
  '  [DllImport("user32.dll")] public static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);',
  "}",
].join("\n");

export const NOACTIVATE_FORM_CS = [
  "using System.Windows.Forms;",
  "public class NoActivateForm : Form {",
  "  protected override CreateParams CreateParams {",
  "    get {",
  "      CreateParams cp = base.CreateParams;",
  "      cp.ExStyle |= 0x08000000;",
  "      return cp;",
  "    }",
  "  }",
  "}",
].join("\n");

export const FIND_TERMINAL_PS = [
  "function Test-TerminalName {",
  "  param([string]$name)",
  "  return $name -match 'WindowsTerminal|OpenConsole|conhost|pwsh|powershell|^cmd$|conemu|cmder|alacritty|wezterm|kitty|konsole|gnome-terminal|xterm|hyper|mintty|tabby|fluentterminal|putty'",
  "}",
  "$script:target = [IntPtr]::Zero",
  "$script:chainWindow = [IntPtr]::Zero",
  "$script:chainPid = 0",
  '$me = Get-CimInstance Win32_Process -Filter "ProcessId=$PID"',
  "$cur = $me.ParentProcessId",
  "for ($i = 0; $i -lt 12 -and $cur -ne 0; $i++) {",
  "  $p = Get-Process -Id $cur -ErrorAction SilentlyContinue",
  "  if ($p -and $p.MainWindowHandle -ne 0) {",
  "    if ($script:chainWindow -eq [IntPtr]::Zero) { $script:chainWindow = $p.MainWindowHandle; $script:chainPid = $p.Id }",
  "    if (Test-TerminalName $p.ProcessName) {",
  "      $script:target = $p.MainWindowHandle",
  "      break",
  "    }",
  "  }",
  '  $w = Get-CimInstance Win32_Process -Filter "ProcessId=$cur" -ErrorAction SilentlyContinue',
  "  if (-not $w) { break }",
  "  $cur = $w.ParentProcessId",
  "}",
  "if ($script:target -eq [IntPtr]::Zero) {",
  "  Get-Process -ErrorAction SilentlyContinue | ForEach-Object {",
  "    if ($script:target -eq [IntPtr]::Zero -and $_.MainWindowHandle -ne 0 -and (Test-TerminalName $_.ProcessName)) {",
  "      $script:target = $_.MainWindowHandle",
  "    }",
  "  }",
  "}",
  "if ($script:target -eq [IntPtr]::Zero -and $script:chainWindow -ne [IntPtr]::Zero) {",
  "  $cw = Get-Process -Id $script:chainPid -ErrorAction SilentlyContinue",
  "  if ($cw -and $cw.ProcessName -ne 'explorer') { $script:target = $script:chainWindow }",
  "}",
].join("\n");

export const FOCUS_TERMINAL_PS = [
  "function Focus-Terminal {",
  '  $diag = Join-Path $env:TEMP "opencode-notify-popup.log"',
  "  if ($script:target -eq [IntPtr]::Zero) { Add-Content -Path $diag -Value \"focus-abort target=0\"; return }",
  "  $fg = [Focuser]::GetForegroundWindow()",
  "  $fgPid = 0",
  "  $fgThread = [Focuser]::GetWindowThreadProcessId($fg, [ref]$fgPid)",
  "  $curThread = [Focuser]::GetCurrentThreadId()",
  '  Add-Content -Path $diag -Value "focus target=$script:target fg=$fg fgPid=$fgPid"',
  "  if ([Focuser]::IsIconic($script:target)) { [Focuser]::ShowWindow($script:target, 9) | Out-Null }",
  "  [Focuser]::AttachThreadInput($fgThread, $curThread, $true) | Out-Null",
  "  [Focuser]::SetForegroundWindow($script:target) | Out-Null",
  "  Start-Sleep -Milliseconds 300",
  "  [Focuser]::AttachThreadInput($fgThread, $curThread, $false) | Out-Null",
  '  Add-Content -Path $diag -Value "focus-after fg=$([Focuser]::GetForegroundWindow())"',
  "}",
].join("\n");
